# Generated by Django 3.2.5 on 2021-07-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costomer',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(verbose_name=10)),
                ('costID', models.IntegerField(primary_key=1, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
            ],
        ),
    ]
