# Generated by Django 3.2.4 on 2021-08-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='costomer',
            new_name='customer',
        ),
    ]
