# Generated by Django 2.2.5 on 2021-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_costomer_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastName',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(default=None, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.IntegerField(default=None, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
