# Generated by Django 3.2.5 on 2021-08-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.BigIntegerField(default=None),
        ),
    ]
